version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "05:24"
  target-branch: main
  labels:
    - CI/CD
    - skip_changelog
- package-ecosystem: pip
  directories:
    - "/"
    - "/.github/utils"
  schedule:
    interval: weekly
    day: monday
    time: "05:18"
  target-branch: main
  labels:
    - dependencies
    - skip_changelog
  groups:
    packages:
      applies-to: version-updates
      patterns: ["*"]
    security:
      applies-to: security-updates
      patterns: ["*"]
