# pre-commit.ci
ci:
  autofix_commit_msg: |
      [pre-commit.ci] auto fixes from pre-commit hooks

      For more information, see https://pre-commit.ci
  autofix_prs: false
  autoupdate_branch: 'main'
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: 'weekly'
  skip: [validate-entities]  # doesn't seem to work. Also, this is checked with dedicated CD workflow
  submodules: false

# hooks
default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: check-toml
      name: Check TOML
    - id: check-yaml
      name: Check YAML
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
      exclude: ^CHANGELOG.md$
    - id: name-tests-test
      args: ["--pytest-test-first"]
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    - id: pyupgrade
      args: [--py39-plus, --keep-runtime-typing]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    - id: black

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
    - id: ruff
      args: ["--fix", "--exit-non-zero-on-fix", "--show-fixes"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
    - id: bandit
      args: ["-r"]
      files: ^oteapi_optimade/.*$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    - id: mypy
      exclude: ^tests/.*$
      additional_dependencies:
        - "types-requests"
        - "pydantic>=2,<3"

  - repo: https://github.com/SINTEF/ci-cd
    rev: v2.9.1
    hooks:
    - id: docs-api-reference
      args:
      - "--package-dir=oteapi_optimade"
      - "--full-docs-folder=models"
    - id: docs-landing-page

  # entities-service can validate SOFT/DLite entities
  # More information can be found in the repository README:
  # https://github.com/SINTEF/entities-service?tab=readme-ov-file#readme
  - repo: https://github.com/SINTEF/entities-service
    rev: v0.7.2
    hooks:
    - id: validate-entities
      additional_dependencies: [".[cli]"]
      files: ^entities/.*\.ya?ml$
