version: "3"

services:
  oteapi:
    image: ghcr.io/emmc-asbl/oteapi:${DOCKER_OTEAPI_VERSION:-latest}
    ports:
      - "${PORT:-8080}:8080"
    environment:
      OTEAPI_REDIS_TYPE: redis
      OTEAPI_REDIS_HOST: redis
      OTEAPI_REDIS_PORT: 6379
      OTEAPI_prefix: "${OTEAPI_prefix:-/api/v1}"
      # OTEAPI_PLUGIN_PACKAGES: "-v -e /oteapi-optimade"
    depends_on:
      - redis
    networks:
      - otenet
    volumes:
      - "${PWD}:/oteapi-optimade"
    entrypoint: /bin/bash -c "pip install -v -e /oteapi-optimade && ./entrypoint.sh"

  redis:
    image: redis:latest
    volumes:
      - redis-persist:/data
    networks:
      - otenet

  sftp:
    image: atmoz/sftp
    volumes:
      - sftp-storage:${HOME:-/home/foo}/download
    command: ${USER:-foo}:${PASSWORD:-pass}:1001
    networks:
      - otenet

  optimade:
    build:
      context: "${PATH_TO_OPT:-/tmp/optimade-python-tools}"
      dockerfile: Dockerfile
      args:
        CONFIG_FILE: .docker/docker_config.json
        PORT: ${OPTIMADE_PORT:-5000}
    environment:
      MAIN: main
      OPTIMADE_CONFIG_FILE: "/app/config.json"
    networks:
      - otenet

volumes:
  redis-persist:
  sftp-storage:

networks:
  otenet:
