name: CI/CD - New updates to 'main'

on:
  push:
    branches: [main]

jobs:
  update-deps-branch-and-docs:
    name: Call external workflow
    uses: CasperWA/ci-cd/.github/workflows/ci_cd_updated_default_branch.yml@v1
    if: github.repository_owner == 'SINTEF'
    with:
      git_username: "TEAM 4.0[bot]"
      git_email: "Team4.0@SINTEF.no"
      permanent_dependencies_branch: "ci/dependency-updates"
      default_repo_branch: main
      package_dir: oteapi_optimade
      update_docs: true
      update_python_api_ref: true
      update_docs_landing_page: true
      python_version: "3.9"
      doc_extras: "[doc]"
      full_docs_dirs: models
    secrets:
      PAT: ${{ secrets.RELEASE_PAT }}
