name: CI - Check dependencies

on:
  schedule:
    # At 7:30 every Monday (5:30 UTC)
    - cron: "30 5 * * 1"
  workflow_dispatch:

jobs:
  check-dependencies:
    name: Call external workflow
    uses: CasperWA/gh-actions/.github/workflows/ci_check_pyproject_dependencies.yml@main
    if: github.repository_owner == 'SINTEF'
    with:
      git_username: "TEAM 4.0[bot]"
      git_email: "Team4.0@SINTEF.no"
      permanent_dependencies_branch: "ci/dependency-updates"
      python_version: "3.9"
      install_extras: "[dev]"
      pr_labels: "CI/CD"
    secrets:
      release_PAT: ${{ secrets.RELEASE_PAT }}
